### ISSUE TITLE
Favorite designs are missing

### ISSUE THREAD

**Issue by rotemmiz** [yershalom/react-wordart#2]
My two favorite designs are missing!!!!
<img width="185" alt="screen shot 2019-02-05 at 22 28 07" src="https://user-images.githubusercontent.com/1361404/52302306-74536880-2995-11e9-8f62-ed6a3066618a.png">
<img width="183" alt="screen shot 2019-02-05 at 22 28 00" src="https://user-images.githubusercontent.com/1361404/52302307-74ebff00-2995-11e9-9475-0f3cd0b30880.png">
Please add, it is very important for our customers!

**Comment by ItamarShDev** [comment]
Maybe need to be added [here](https://github.com/yershalom/css-wordart) first?

**Comment by rotemmiz** [comment]
You are right!
https://github.com/yershalom/css-wordart/issues/2

**Comment by yershalom** [comment]
Moved
