### ISSUE TITLE
The biggest pivot ever happened or a mistake?

### ISSUE THREAD

**Issue by ItamarShDev** [yershalom/react-wordart#5]
https://github.com/yershalom/react-wordart/compare/871ba2e63f6eae00fac67d95810e9743866fe95a..a6904838deab4d4f9f6fc785d7a569cf4c2a6d0e

this push force,  change the _WHOLE REPOSITORY_

**Comment by yershalom** [comment]
Mistake

**Comment by ItamarShDev** [comment]
:+1:
